LW:
  dt: 0.005
  decimation: 4
  fixed_kp: [80.0, 80.0, 
             50.0, 50.0,
             50.0, 50.0,
             20.0, 20.0,
             20.0, 20.0]
  fixed_kd: [3.0, 3.0,
             3.0, 3.0,
             3.0, 3.0,
             3.0, 3.0,
             3.0, 3.0]
  num_of_dofs: 10
  wheel_indices: [8, 9]
  torque_limits: [120.0, 120.0,
                  120.0, 120.0,
                  120.0, 120.0, 
                  27.0,  27.0,
                  40.0,  40.0]
  default_dof_pos_leg: [0.0, 0.0,
                        0.3491, 0.3491,
                        2.269, 2.269,
                        0.00, 0.00,
                        0.5236, 0.5236]
  default_dof_pos_wheel: [0.0, 0.0,
                          0.3491, 0.3491,
                          2.269, 2.269,
                          0.5236, 0.5236,
                          0.00, 0.00]
  gait_command: [2.0, 0.5, 0.5, 0.25]
  joint_names: ["right_hip_joint", "left_hip_joint",
                "right_thigh_joint", "left_thigh_joint",
                "right_shank_joint", "left_shank_joint",
                "right_foot_joint", "left_foot_joint",
                "right_wheel_joint", "left_wheel_joint"]
  joint_controller_names: ["right_hip_controller", "left_hip_controller",
                           "right_thigh_controller", "left_thigh_controller",
                           "right_shank_controller", "left_shank_controller",
                           "right_foot_controller", "left_foot_controller",
                           "right_wheel_controller", "left_wheel_controller"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
