LW:
  dt: 0.005
  decimation: 4
  fixed_kp: [80.0, 80.0, 
             80.0, 80.0,
             80.0, 80.0,
             80.0, 80.0,
             80.0, 80.0]
  fixed_kd: [3.0, 3.0,
             3.0, 3.0,
             3.0, 3.0,
             3.0, 3.0,
             3.0, 3.0]
  num_of_dofs: 10
  wheel_indices: [6, 7]
  torque_limits: [120.0, 120.0,
                  120.0, 120.0,
                  120.0, 120.0, 
                  40.0,  40.0,
                  40.0,  40.0]
  default_dof_pos: [0.0, 0.0,
                    0.0, 0.0,
                    1.178, 1.178,
                    0.00, 0.00,
                    0.0, 0.0]
  joint_names: ["right_hip_joint", "left_hip_joint",
                "right_thigh_joint", "left_thigh_joint",
                "right_shank_joint", "left_shank_joint",
                "right_wheel_joint", "left_wheel_joint",
                "right_foot_joint", "left_foot_joint"]
  joint_controller_names: ["right_hip_controller", "left_hip_controller",
                           "right_thigh_controller", "left_thigh_controller",
                           "right_shank_controller", "left_shank_controller",
                           "right_wheel_controller", "left_wheel_controller",
                           "right_foot_controller", "left_foot_controller"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
